language: go

sudo: false

go:
  - 1.9
  - "1.10"
  - master

install:
  - make install-deps

env:
  - KCACHE_TEST_ASYNC_DURATION=50ms

script: |
  make test-full && \
  if [ "$TRAVIS_GO_VERSION" == "1.10" ]; then
    travis_wait 30 make test-cover
  fi
